name: FB Proxy Auto Update

on:
  schedule:
    - cron: '*/5 * * * *' # প্রতি ৫ মিনিট
  workflow_dispatch:

jobs:
  run-updater:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Modules
        run: pip install requests[socks]

      - name: Execute Scraper
        run: python proxy_bot.py

      - name: Push Updates
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "ProxyBot"
          git add live_proxies.txt
          git commit -m "Update FB Proxies: $(date)" || exit 0
          git push
